// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDge99EOnB2FtTEucsM-1fPn90tLdD54-s',
    appId: '1:167124465577:web:88ac3318edc289f194b6b8',
    messagingSenderId: '167124465577',
    projectId: 'endpoint-integ-gitactions',
    authDomain: 'endpoint-integ-gitactions.firebaseapp.com',
    storageBucket: 'endpoint-integ-gitactions.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyqZvSy3QDKYTniHXOKEMer4hpe-9O3dY',
    appId: '1:167124465577:android:acd11ad1a4e8b01d94b6b8',
    messagingSenderId: '167124465577',
    projectId: 'endpoint-integ-gitactions',
    storageBucket: 'endpoint-integ-gitactions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1odUBlv-SJlnOPW-NCGo96rl0sE-P5Cc',
    appId: '1:167124465577:ios:171e77ca3eea5f2b94b6b8',
    messagingSenderId: '167124465577',
    projectId: 'endpoint-integ-gitactions',
    storageBucket: 'endpoint-integ-gitactions.firebasestorage.app',
    iosBundleId: 'com.example.endpointIntegrationWithGithubActions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1odUBlv-SJlnOPW-NCGo96rl0sE-P5Cc',
    appId: '1:167124465577:ios:171e77ca3eea5f2b94b6b8',
    messagingSenderId: '167124465577',
    projectId: 'endpoint-integ-gitactions',
    storageBucket: 'endpoint-integ-gitactions.firebasestorage.app',
    iosBundleId: 'com.example.endpointIntegrationWithGithubActions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDge99EOnB2FtTEucsM-1fPn90tLdD54-s',
    appId: '1:167124465577:web:378f07d18aa3312e94b6b8',
    messagingSenderId: '167124465577',
    projectId: 'endpoint-integ-gitactions',
    authDomain: 'endpoint-integ-gitactions.firebaseapp.com',
    storageBucket: 'endpoint-integ-gitactions.firebasestorage.app',
  );
}