name: Flutter CI/CD with github actions

# github trigger
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_apk:
    name: Github repository code fetch, flutter setup and apk build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4.5.0
        with:
          distribution: zulu
          java-version: "17"
      
      # # secrets. variables are stored as secrets and variables of actions in github
      # # the contents of the secret variable are saved in a specific file
      - name: Decode google-services.json
        env: 
            GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{secrets.FIREBASE_OPTION}}
        run : echo "$firebase_options_dart" > lib/firebase_options.dart

      - name: Decode .env file
        env:
          firebase_options_dart: ${{secrets.ENV_FILE}}
        run : echo "$env" > .env
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # - name: Run tests
      #   run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{secrets.FIREBASE_APK_ID}}
            serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CREDENTIAL }}
            groups: tester_group
            file: build/app/outputs/apk/release/app-release.apk
